doctrine_migrations:
    # dir_name: '%kernel.project_dir%/src/Migrations'
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
    # namespace: DoctrineMigrations

    # fixes for doctrine 2.
    migrations_paths:
       # namespace is arbitrary but should be different from App\Migrations
       # as migrations classes should NOT be autoloaded
       'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'
